### ISSUE TITLE
强制横屏

### ISSUE THREAD

**Issue by GrakePch** [C6H5-NO2/EAxT#1]
订餐页面是否有更好的竖屏处理方式？

**Comment by C6H5-NO2** [comment]
I haven’t figured out how to display a vertical list elegantly yet. Any suggestions would be appreciated.

**Comment by HurryPeng** [comment]
We can try deleting the RadioButtons on the right and use onItemClick of the ListView instead to change the number of dishes to be ordered, which will save some space and make it possible to display a vertical ListView.

**Comment by C6H5-NO2** [comment]
@GrakePch See #2
